### ISSUE TITLE
Dashboard  cannot access

### ISSUE THREAD

**Issue by pengisgood** [rootsongjc/kubernetes-vagrant-centos-cluster#9]
和这个 https://github.com/rootsongjc/kubernetes-vagrant-centos-cluster/issues/6 有点类似，但是稍微有区别：Dashboard 的 pod 根本起不来
```
[root@node1 hack]# kubectl get pods --all-namespaces
NAMESPACE     NAME                                   READY     STATUS             RESTARTS   AGE
kube-system   coredns-6558b6549d-zs9dt               1/1       Running            0          32m
kube-system   kubernetes-dashboard-f95796d57-g6m9g   0/1       CrashLoopBackOff   11         32m
kube-system   traefik-ingress-controller-kzqvt       1/1       Running            0          32m

[root@node1 hack]# kubectl get svc --all-namespaces
NAMESPACE     NAME                      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
default       kubernetes                ClusterIP   10.254.0.1       <none>        443/TCP           4d
kube-system   kube-dns                  ClusterIP   10.254.0.2       <none>        53/UDP,53/TCP     34m
kube-system   kubernetes-dashboard      ClusterIP   10.254.113.186   <none>        8443/TCP          34m
kube-system   traefik-ingress-service   ClusterIP   10.254.167.251   <none>        80/TCP,8080/TCP   34m

[root@node1 hack]# docker images
REPOSITORY                                       TAG                 IMAGE ID            CREATED             SIZE
docker.io/jimmysong/kubernetes-dashboard-amd64   v1.8.2              c87ea0497294        3 months ago        102 MB
docker.io/jimmysong/pause-amd64                  3.0                 99e59f495ffa        23 months ago       747 kB

[root@node1 hack]# docker run -it docker.io/jimmysong/kubernetes-dashboard-amd64:v1.8.2 bash
2018/04/16 17:13:43 Starting overwatch
2018/04/16 17:13:43 Using in-cluster config to connect to apiserver
2018/04/16 17:13:43 Could not init in cluster config: unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined
2018/04/16 17:13:43 Using random key for csrf signing
2018/04/16 17:13:43 No request provided. Skipping authorization
panic: Could not create client config. Check logs for more information

goroutine 1 [running]:
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).initInsecureClient(0xc4201632c0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:335 +0x9a
github.com/kubernetes/dashboard/src/app/backend/client.(*clientManager).init(0xc4201632c0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:297 +0x47
github.com/kubernetes/dashboard/src/app/backend/client.NewClientManager(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/client/manager.go:365 +0x84
main.main()
	/home/travis/build/kubernetes/dashboard/.tmp/backend/src/github.com/kubernetes/dashboard/src/app/backend/dashboard.go:91 +0x13b
```
我通过查看 docker containers 发现dashboard 的容器没有起来，尝试手动启 dashboard 的容器，结果报上面👆这个错误。

```
[root@node1 hack]# systemctl status kube-apiserver -a
● kube-apiserver.service - Kubernetes API Service
   Loaded: loaded (/usr/lib/systemd/system/kube-apiserver.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-04-16 23:06:31 CST; 2h 13min ago
     Docs: https://github.com/GoogleCloudPlatform/kubernetes
 Main PID: 1217 (kube-apiserver)
   Memory: 2.6M
   CGroup: /system.slice/kube-apiserver.service
           └─1217 /usr/bin/kube-apiserver --logtostderr=true --v=0 --etcd-servers=http://172.17.8.101:2379,http://172.17.8.102:2379,http://172.17.8.103:2379 --advertise-addres...

Apr 17 01:01:43 node1 kube-apiserver[1217]: I0417 01:01:43.675007    1217 logs.go:49] http: TLS handshake error from 172.17.8.1:62897: EOF
Apr 17 01:01:43 node1 kube-apiserver[1217]: I0417 01:01:43.807961    1217 logs.go:49] http2: server: error reading preface from client 172.17.8.1:62898: read tcp 172.17.8.101:6443->172.17.8.1:62898: read: connection reset by peer
Apr 17 01:02:22 node1 kube-apiserver[1217]: I0417 01:02:22.100809    1217 logs.go:49] http: TLS handshake error from 172.17.8.101:56790: remote error: tls: unknown certificate authority
Apr 17 01:05:23 node1 kube-apiserver[1217]: I0417 01:05:23.383208    1217 trace.go:76] Trace[932644373]: "List /api/v1/componentstatuses" (started: 2018-04-17 01:05:20.376024136 +0800 CST m=+7136.859394663) (total time: 3.007151421s):
Apr 17 01:05:23 node1 kube-apiserver[1217]: Trace[932644373]: [3.007009003s] [3.006957743s] Listing from storage done
Apr 17 01:08:11 node1 kube-apiserver[1217]: I0417 01:08:11.716342    1217 logs.go:49] http: TLS handshake error from 172.17.8.1:62985: EOF
Apr 17 01:08:51 node1 kube-apiserver[1217]: I0417 01:08:51.101732    1217 logs.go:49] http2: received GOAWAY [FrameHeader GOAWAY len=33], starting graceful shutdown
Apr 17 01:16:56 node1 kube-apiserver[1217]: I0417 01:16:56.548936    1217 logs.go:49] http: TLS handshake error from 172.17.8.1:63062: EOF
Apr 17 01:16:58 node1 kube-apiserver[1217]: I0417 01:16:58.937833    1217 logs.go:49] http: TLS handshake error from 172.17.8.1:63063: EOF
Apr 17 01:16:59 node1 kube-apiserver[1217]: I0417 01:16:59.109004    1217 logs.go:49] http2: server: error reading preface from client 172.17.8.1:63064: read tcp 172.17.8.101:6443->172.17.8.1:63064: read: connection reset by peer
```

**Comment by starjason** [comment]
kubernetes-client-linux-amd64.tar.gz
kubernetes-server-linux-amd64.tar.gz

这2个文件 你的是什么版本？

我一开始用的1.10.0的版本，连集群都起不来，试了好几遍之后，怀疑是兼容性问题，于是换回1.9.3版本。

**Comment by pengisgood** [comment]
我从官网下的是1.10.0的。

**Comment by starjason** [comment]
CrashLoopBackOff 表明容器曾经启动了，但又异常退出了。查一下日志吧。

kubectl logs -f kubernetes-dashboard-f95796d57-g6m9g

显示什么？

**Comment by pengisgood** [comment]
晚点贴上 log，刚刚把虚拟机都停了。 :(

**Comment by pengisgood** [comment]
```
[root@node1 ~]# docker ps -a
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS                     PORTS               NAMES
602620e806e5        c87ea0497294                                            "/dashboard --inse..."   4 seconds ago       Exited (1) 3 seconds ago                       k8s_kubernetes-dashboard_kubernetes-dashboard-f95796d57-g6m9g_kube-system_89351197-4194-11e8-a66d-525400ad3b43_26
44eeb072d9f4        jimmysong/pause-amd64:3.0                               "/pause"                 11 minutes ago      Up 11 minutes                                  k8s_POD_kubernetes-dashboard-f95796d57-g6m9g_kube-system_89351197-4194-11e8-a66d-525400ad3b43_1
d16c6e42a4a8        docker.io/jimmysong/kubernetes-dashboard-amd64:v1.8.2   "/dashboard --inse..."   22 hours ago        Exited (2) 22 hours ago                        sad_minsky
d2912eeb3f4b        c87ea0497294                                            "/dashboard --inse..."   22 hours ago        Exited (2) 22 hours ago                        inspiring_liskov

[root@node1 ~]# docker logs -f 602620e806e5
2018/04/17 15:37:02 Using in-cluster config to connect to apiserver
2018/04/17 15:37:02 Using service account token for csrf signing
2018/04/17 15:37:02 No request provided. Skipping authorization
2018/04/17 15:37:02 Starting overwatch
2018/04/17 15:37:02 Successful initial request to the apiserver, version: v1.10.0
2018/04/17 15:37:02 Generating JWE encryption key
2018/04/17 15:37:03 New synchronizer has been registered: kubernetes-dashboard-key-holder-kube-system. Starting
2018/04/17 15:37:03 Starting secret synchronizer for kubernetes-dashboard-key-holder in namespace kube-system
2018/04/17 15:37:03 Initializing JWE encryption key from synchronized object
2018/04/17 15:37:03 Creating in-cluster Heapster client
2018/04/17 15:37:03 Auto-generating certificates
2018/04/17 15:37:03 [ECDSAManager] Failed to open dashboard.crt for writing: open /certs/dashboard.crt: read-only file system
```

看上去是没有写文件的权限？

**Comment by pengisgood** [comment]
当我把 kubernetes server 和 client 的版本降级为1.9.1 启动起来完全没有问题了。

**Comment by emperorente** [comment]
Try to replace the default dashboard URL to "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.8.3",  Reinstall, peace and quiet.
Kubernetes version:1.10

**Comment by harikrishp** [comment]
I'm facing the same issue, I have used the dashboard URL of v.1.8.3 and Kubernetes version: v.1.8.4.
Can someone please help me.

**Comment by Lemon-le** [comment]
我的也是同样的问题

**Comment by jahentao** [comment]
I have the same question.
